# arguments for dataset
dataset: tpo
nclass: 3
crop_size: 320
data_root: /data/Data/TPO

# arguments for training
epochs: 80
batch_size: 2 # per GPU x 48 GPUs
lr: 0.001
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: deeplabv3plus
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
